### ISSUE TITLE
Debian 10 tex

### ISSUE THREAD

**Issue by rlfnb** [wipatrick/latex-vorlage-thesis#4]
`
$ pdflatex -shell-escape thesis-doc.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2019/dev/Debian) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
(./thesis-doc.tex
LaTeX2e <2018-12-01>
(/usr/share/texlive/texmf-dist/tex/latex/koma-script/scrreprt.cls
Document Class: scrreprt 2019/02/01 v3.26b KOMA-Script document class (report)
(/usr/share/texlive/texmf-dist/tex/latex/koma-script/scrkbase.sty
(/usr/share/texlive/texmf-dist/tex/latex/koma-script/scrbase.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/latex/koma-script/scrlfile.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/koma-script/tocbasic.sty)
(/usr/share/texlive/texmf-dist/tex/latex/koma-script/scrsize11pt.clo)
(/usr/share/texlive/texmf-dist/tex/latex/koma-script/typearea.sty

Package typearea Warning: You've used obsolete option `BCOR10mm'.
(typearea)                Usage of this option indicates an old document
(typearea)                and changes compatibility level using
(typearea)                `BCOR=10mm,version=first,
(typearea)                enabledeprecatedfontcommands' that may result
(typearea)                in further warnings.
(typearea)                If you don't want this, you should simply
(typearea)                replace option `BCOR10mm' by `BCOR=10mm'.

)) (/usr/share/texlive/texmf-dist/tex/latex/etex-pkg/etex.sty)
! Missing \endcsname inserted.
<to be read again> 
                   \unhbox 
l.31 \input{präambel/package}
                              
? q
`
Ein Umbennen `mv präambel praeambel` und das Aendern des Dateinamens in Zeile 31 beheben den ersten Fehler.

`! LaTeX Error: File `multirow.sty' not found` wird behoben durch Installieren von 
`apt install texlive-latex-extra`

`! LaTeX Error: File `algorithm2e.sty' not found.` wird behoben durch Installieren von `apt install texlive-science`

`! LaTeX Error: File `esvect.sty' not found.` wird behoben durch Installieren von `apt install texlive-fonts-extra` was kein Spass ist (1200 MB Plattenplatz!!!).

Danach ist alles baubar

**Comment by adbuerger** [comment]
Hello @rlfnb thank you for your feedback. We typically install `texlive-full` to get all necessary packages, as disk space is usually not a problem today. In addition to the packages you described above, which ones did you need to install to get it working? Only `texlive-base`?

Anyways, renaming "präambel" to "praeambel" is probably a good idea, thank you for pointing this out.

**Comment by rlfnb** [comment]
Yes, installed texlive-base, disk space might be not a big issue on desktop machines, but docker images might benefit from it as well :) Thanks for caring!
